name: creditform
description: CreditForm Complete Project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  shared_preferences: ^2.2.2     # ✅ Salvataggio stato corsi
  webview_flutter: ^4.7.0        # ✅ Per incorporare i video da Bunny (Android/iOS)
  intl: ^0.18.1                  # ✅ Per formattare le date nei progressi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0          # ✅ Per evitare warning e lint errors

flutter:
  uses-material-design: true     # ✅ Abilita i widget Material
