// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvg-vsDo-8sFzo6jVbeUWrRPEyFreO32I',
    appId: '1:418457726672:web:4d0d18604a93fbdd93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    authDomain: 'creditform-d505d.firebaseapp.com',
    storageBucket: 'creditform-d505d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeedNoxxo1sTVo_j53MmUcXtofQwls48',
    appId: '1:418457726672:android:6e125bd4e602500a93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCnuQkrW6YE4VSaoqhzngn_5iJ8LUO2A',
    appId: '1:418457726672:ios:c62a1c8b80aafad193f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.firebasestorage.app',
    iosBundleId: 'com.example.creditform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCnuQkrW6YE4VSaoqhzngn_5iJ8LUO2A',
    appId: '1:418457726672:ios:c62a1c8b80aafad193f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    storageBucket: 'creditform-d505d.firebasestorage.app',
    iosBundleId: 'com.example.creditform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvg-vsDo-8sFzo6jVbeUWrRPEyFreO32I',
    appId: '1:418457726672:web:84c8ae59a910794b93f8d5',
    messagingSenderId: '418457726672',
    projectId: 'creditform-d505d',
    authDomain: 'creditform-d505d.firebaseapp.com',
    storageBucket: 'creditform-d505d.firebasestorage.app',
  );
}